#配置数据源---阿里云数据库RDS
spring:
  datasource:
    url: jdbc:mysql://rm-bp1lz1g29baqsww894o.mysql.rds.aliyuncs.com:3306/wiki?charaterEncoding=UTF8&&autoReconnect=true&allowMultiQueries=true
    username: wiki
    password: Zengzhaoyang123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 25
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      connection-timeout: 30000
      max-lifetime: 1800000
      connection-test-query: SELECT 1

      #增加redis的配置
  redis:
    host: r-bp1vf1nl7i07q6iavwpd.redis.rds.aliyuncs.com
    port: 6379
    password: Redis000
#rocketmq配置
  rocketmq:
    name-server: 127.0.0.1:9876
    producer:
      group: defalut


#配置mybatis所有的Mpper.xml所在的路径
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    com:
      zzy:
        wiki:
          mapper: trace



